apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibana.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "kibana.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
